### ISSUE TITLE
Duplicated source files in the project

### ISSUE THREAD

**Issue by douglascrp** [ITDSystems/alvex-utils#10]
Hello.

I was checking for some error messages in my server containing this addon installed, and ended up finding that the project has duplicated source files.

Files containing exact same content:
https://github.com/ITDSystems/alvex-utils/blob/master/repo/src/main/amp/config/alfresco/extension/alvex-extension-registry-cron-context.xml
and
https://github.com/ITDSystems/alvex-utils/blob/master/repo/src/main/amp/config/alfresco/module/utils/context/alvex-extension-registry-cron-context.xml

Files containing similar content:
https://github.com/ITDSystems/alvex-utils/blob/master/repo/src/main/amp/config/alfresco/extension/alvex-extension-registry-context.xml
and
https://github.com/ITDSystems/alvex-utils/blob/master/repo/src/main/amp/config/alfresco/module/utils/context/alvex-extension-registry-context.xml

I guess the right one that should stay in the project are the ones inside the module/utils folder.
Am I right?

**Comment by aviriel** [comment]
fixed this, thanks
