### ISSUE TITLE
Job extension-registry-job-group.extension-registry-check-updates-job threw an unhandled Exception:  org.alfresco.service.cmr.repository.TemplateException: 08256687 Erro durante o processamento do modelo 'No nodes selected

### ISSUE THREAD

**Issue by douglascrp** [ITDSystems/alvex-utils#11]
The alvex-utils projects has the following scheduled action configured to search for a javascript file that is not part of the project itself.

The javascript file is referenced at https://github.com/ITDSystems/alvex-utils/blob/master/repo/src/main/amp/config/alfresco/module/utils/context/alvex-extension-registry-cron-context.xml#L25

But the referenced javascript file is part of the alvex-orgchart project
https://github.com/ITDSystems/alvex-orgchart/blob/master/repo/src/main/amp/config/alfresco/bootstrap/alvex_check_major_updates.js

So, the right thing to do is to move the alvex_check_major_updates.js into this project or to more the scheduled action into the alvex-orgchart project.

I am able to fix it for you, but I need to know which approach would be better to you.
I believe the first one is better, as I see the version check as something used for all the components, and not for alvex-orgchart.

**Comment by douglascrp** [comment]
As a workaround, in order to stop seeing the error messages, one can simply upload the file alvex_check_major_updates.js into the **Data Dictionary/Scripts** folder

**Comment by aviriel** [comment]
I prefer another way to solve this :)

**Comment by douglascrp** [comment]
So, I guess it was no more relevant for the project, right?

**Comment by aviriel** [comment]
yep, there is no resource that tells Alvex installations about new versions

**Comment by douglascrp** [comment]
Got it.

Thank you.
